import type { GetServerSideProps } from "next";
import Head from "next/head";
import FlightDetails from "../../components/FlightDetails";
import { Launch } from "../../types/FlightListTypes";
import Layout from "../../components/Layout";
import { initializeApollo, addApolloState } from "../../lib/apolloClient";
import { gql } from "@apollo/client";

interface LaunchDetailsPageProps {
  data: Launch;
}

export const LAUNCH_DETAILS_QUERY = gql`
  query launch($id: ID!) {
    launch(id: $id) {
      mission_name
      details
      launch_success
      launch_date_local
      links {
        article_link
        flickr_images
        video_link
      }
      rocket {
        rocket_name
        rocket_type
        first_stage {
          cores {
            landing_vehicle
            flight
            landing_type
            land_success
            landing_intent
            reused
          }
        }
        second_stage {
          payloads {
            id
            reused
            payload_type
            payload_mass_kg
            orbit
            nationality
            manufacturer
            customers
          }
        }
      }
    }
  }
`;

const LaunchDetailsPage = ({ data }: LaunchDetailsPageProps) => {
  return (
    <>
      <Head>
        <title>SpaceX Launches - details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <FlightDetails data={data} />
      </Layout>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async ({ params }) => {
  const apolloClient = initializeApollo();

  const queryVariables = {
    id: params?.id,
  };

  const { data } = await apolloClient.query({
    query: LAUNCH_DETAILS_QUERY,
    variables: queryVariables,
  });

  return {
    props: {
      data: data.launch,
    },
  };
};

export default LaunchDetailsPage;
