import type { GetServerSideProps } from "next";
import Head from "next/head";
import FlightDetails from "../../components/FlightDetails";
import { Launch } from "../../types/FlightListTypes";
import Layout from "../../components/Layout";
import { initializeApollo } from "../../lib/apolloClient";
import LAUNCH_DETAILS_QUERY from "../../schemas/launch";

interface LaunchDetailsPageProps {
  data: Launch;
}

const LaunchDetailsPage = ({ data }: LaunchDetailsPageProps) => {
  return (
    <>
      <Head>
        <title>SpaceX Launches - details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <FlightDetails data={data} />
      </Layout>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async ({ params }) => {
  try {
    const apolloClient = initializeApollo();

    const queryVariables = {
      id: params?.id,
    };

    const { data } = await apolloClient.query({
      query: LAUNCH_DETAILS_QUERY,
      variables: queryVariables,
    });

    if (!data.launch) {
      throw new Error();
    }

    return {
      props: {
        data: data.launch,
      },
    };
  } catch (e) {
    return { notFound: true };
  }
};

export default LaunchDetailsPage;
