import type { GetServerSideProps } from "next";
import Head from "next/head";
import FlightDetails from "../../components/FlightDetails";
import { Launch } from "../../types/FlightListTypes";
import Layout from "../../components/Layout";

interface LaunchDetailsPageProps {
  data: Launch;
}

const LaunchDetailsPage = ({ data }: LaunchDetailsPageProps) => {
  return (
    <>
      <Head>
        <title>SpaceX Launches - list</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <FlightDetails data={data} />
      </Layout>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const response = await fetch(
    `https://api.spacexdata.com/v3/launches/${context?.params?.id}`
  );
  const data = await response.json();

  return {
    props: {
      data,
    },
  };
};

export default LaunchDetailsPage;
