import type { GetServerSideProps, GetStaticProps } from 'next'
import { useEffect, useState } from 'react';
import Head from 'next/head'
import FlightList from '../components/FlightList'
import styles from '../styles/Home.module.css'
import { Launch } from '../types/FlightListTypes'

interface FlightListPageProps {
  initialLaunches: Launch[];
}

const FlightListPage = ({ initialLaunches }: FlightListPageProps) => {
  const [page, setPage] = useState(0);
  const [perPage, setPerPage] = useState(10);
  const [launches, setLaunches] = useState(initialLaunches);
  const [isFirstRender, setIsFirstRender] = useState(true);

  useEffect(() => {
    if (isFirstRender) {
      setIsFirstRender(false);

      return;
    }
    const fetchLaunches = async () => {
      const response = await fetch(`https://api.spacexdata.com/v3/launches?offset=${page * perPage}&limit=${perPage}`);
      const launches = await response.json();

      setLaunches(launches);
    }

    fetchLaunches();
  }, [page, perPage]);

  const paginationProps = {
    page,
    perPage,
    setPage,
    setPerPage
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>SpaceX Launches - list</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          SpaceX Launches
        </h1>

        <FlightList launches={launches} {...paginationProps}/>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.omnicalculator.com/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by Damian Styczeń for Omni Calculator
        </a>
      </footer>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  const page = Number(query.page) || 1;
  const perPage = Number(query.perPage) || 10;

  const response = await fetch(`https://api.spacexdata.com/v3/launches?page=${page * perPage}&limit=${perPage}`);
  const initialLaunches = await response.json();

  return {
    props: {
      initialLaunches,

    }
  }
}

export default FlightListPage
