import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import FlightList from '../components/FlightList'
import styles from '../styles/Home.module.css'
import { Launch } from '../types/FlightListTypes'

interface FlightListPageProps {
  launches: Launch[];
}

const FlightListPage = ({ launches }: FlightListPageProps) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>SpaceX Launches - list</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          SpaceX Launches
        </h1>

        <FlightList launches={launches} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.omnicalculator.com/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by Damian Styczeń for Omni Calculator
        </a>
      </footer>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const response = await fetch('https://api.spacexdata.com/v3/launches?limit=10');
  const launches = await response.json();

  return {
    props: {
      launches
    }
  }
}

export default FlightListPage
